version: '3.4'

services:
  db:
    image: api-asp-net-core-5-mysql-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile    
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - "3308:3306"
    networks:
      - udemy-network
      
  api-asp-net-core-5:
    image: api-asp-net-core-5
    restart: always
    build:
      context: .
      dockerfile: APIAspNetCore5/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - udemy-network

networks: 
  udemy-network:
    driver: bridge