sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 2.0.0
services: docker
before_install:
  - cd 20_APIAspNetCore5_AddingDockerSupport/
script:
  - docker-compose build
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
deploy:
  provider: script
  script:
    docker tag api-asp-net-core-5:latest $DOCKER_USERNAME/api-asp-net-core-5:latest;
    docker push $DOCKER_USERNAME/api-asp-net-core-5:latest;
  on:
    brach: master
notifications:
  email: false