name: Docker Image CI

on: [push]

env:
  IMAGE_NAME: api-asp-net-core-5

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker Login - Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}

    - name: Build images
      working-directory: ./20_APIAspNetCore5_AddingDockerSupport
      run: docker-compose build        

    - name: Push to Azure Container Registry
      run: |
          docker tag $IMAGE_NAME:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/$IMAGE_NAME:${{github.run_id}}
          docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/$IMAGE_NAME:${{github.run_id}}

    - name: Login in Azure to Deployment
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure WebApp Container - Application Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: erudio-api-server
        images: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/$IMAGE_NAME:latest
